In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [32]:
data=pd.read_csv(r"C:\Users\reshm\Downloads\train_LZdllcl.csv")

In [33]:
data.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   employee_id           54808 non-null  int64  
 1   department            54808 non-null  object 
 2   region                54808 non-null  object 
 3   education             52399 non-null  object 
 4   gender                54808 non-null  object 
 5   recruitment_channel   54808 non-null  object 
 6   no_of_trainings       54808 non-null  int64  
 7   age                   54808 non-null  int64  
 8   previous_year_rating  50684 non-null  float64
 9   length_of_service     54808 non-null  int64  
 10  KPIs_met >80%         54808 non-null  int64  
 11  awards_won?           54808 non-null  int64  
 12  avg_training_score    54808 non-null  int64  
 13  is_promoted           54808 non-null  int64  
dtypes: float64(1), int64(8), object(5)
memory usage: 5.9+ MB


In [35]:
data.shape

(54808, 14)

In [36]:
data['employee_id'].nunique()

54808

In [37]:
data=data.drop(['employee_id'],axis=1)

In [38]:
data.isna().sum()

department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [39]:
data['education']=data['education'].fillna(data['education'].mode()[0])
data['previous_year_rating']=data['previous_year_rating'].fillna(data['previous_year_rating'].median())

In [40]:
data.isna().sum()

department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [41]:
data.columns

Index(['department', 'region', 'education', 'gender', 'recruitment_channel',
       'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service',
       'KPIs_met >80%', 'awards_won?', 'avg_training_score', 'is_promoted'],
      dtype='object')

## Encoding

In [42]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [43]:
obj=['department','region','education','gender','recruitment_channel']
for i in obj:
    data[i]=le.fit_transform(data[i])

In [44]:
data.head()

department  region  education  gender  recruitment_channel  \
0           7      31          2       0                    2   
1           4      14          0       1                    0   
2           7      10          0       1                    2   
3           7      15          0       1                    0   
4           8      18          0       1                    0   

   no_of_trainings  age  previous_year_rating  length_of_service  \
0                1   35                   5.0                  8   
1                1   30                   5.0                  4   
2                1   34                   3.0                  7   
3                2   39                   1.0                 10   
4                1   45                   3.0                  2   

   KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
0              1            0                  49            0  
1              0            0                  60            0  
2              0            0                  50            0  
3              0            0                  50            0  
4              0            0                  73            0

In [45]:
data.describe()

department        region     education        gender  \
count  54808.000000  54808.000000  54808.000000  54808.000000   
mean       4.972796     15.428970      0.559316      0.702379   
std        2.506046      8.764954      0.889452      0.457216   
min        0.000000      0.000000      0.000000      0.000000   
25%        4.000000     11.000000      0.000000      0.000000   
50%        5.000000     14.000000      0.000000      1.000000   
75%        7.000000     21.000000      2.000000      1.000000   
max        8.000000     33.000000      2.000000      1.000000   

       recruitment_channel  no_of_trainings           age  \
count         54808.000000     54808.000000  54808.000000   
mean              0.868158         1.253011     34.803915   
std               0.980713         0.609264      7.660169   
min               0.000000         1.000000     20.000000   
25%               0.000000         1.000000     29.000000   
50%               0.000000         1.000000     33.000000   
75%               2.000000         1.000000     39.000000   
max               2.000000        10.000000     60.000000   

       previous_year_rating  length_of_service  KPIs_met >80%   awards_won?  \
count          54808.000000       54808.000000   54808.000000  54808.000000   
mean               3.304481           5.865512       0.351974      0.023172   
std                1.214770           4.265094       0.477590      0.150450   
min                1.000000           1.000000       0.000000      0.000000   
25%                3.000000           3.000000       0.000000      0.000000   
50%                3.000000           5.000000       0.000000      0.000000   
75%                4.000000           7.000000       1.000000      0.000000   
max                5.000000          37.000000       1.000000      1.000000   

       avg_training_score   is_promoted  
count        54808.000000  54808.000000  
mean            63.386750      0.085170  
std             13.371559      0.279137  
min             39.000000      0.000000  
25%             51.000000      0.000000  
50%             60.000000      0.000000  
75%             76.000000      0.000000  
max             99.000000      1.000000

In [46]:
x=data.drop(['is_promoted'],axis=1)
y=data['is_promoted']

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

## Logistic Regression

In [49]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()

In [50]:
log_reg=log_reg.fit(x_train,y_train)

In [51]:
y_pred=log_reg.predict(x_test)

In [52]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [53]:
print('Accuracy is:',accuracy_score(y_test,y_pred))

Accuracy is: 0.9166545029922639


In [54]:
print('Precision is:',precision_score(y_test,y_pred))

Precision is: 0.47368421052631576


In [55]:
print('Recall Score:',recall_score(y_test,y_pred))

Recall Score: 0.08753315649867374


In [56]:
print('F1 score',f1_score(y_test,y_pred))

F1 score 0.14776119402985075


In [57]:
confusion_matrix(y_test,y_pred)

array([[12461,   110],
       [ 1032,    99]])

## Random Forest

In [58]:
from sklearn.ensemble import RandomForestClassifier

In [59]:
rf_cls=RandomForestClassifier(n_estimators=200)
rf_cls=rf_cls.fit(x_train,y_train)

In [60]:
y_pred_rf=rf_cls.predict(x_test)

In [61]:
print('Accuracy is:',accuracy_score(y_test,y_pred_rf))
print('Precision is:',precision_score(y_test,y_pred_rf))
print('Recall Score:',recall_score(y_test,y_pred_rf))
print('F1 score',f1_score(y_test,y_pred_rf))

Accuracy is: 0.936870529849657
Precision is: 0.8375634517766497
Recall Score: 0.2917771883289125
F1 score 0.43278688524590164


In [62]:
confusion_matrix(y_test,y_pred_rf)

array([[12507,    64],
       [  801,   330]])

## Cross Validation

In [63]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
skfold_model=StratifiedKFold(n_splits=10)

In [64]:
cv_result=cross_val_score(rf_cls,x,y,cv=skfold_model)

In [65]:
cv_result

array([0.93596059, 0.93705528, 0.93066959, 0.93577814, 0.93048714,
       0.93541325, 0.93468345, 0.93778508, 0.93357664, 0.93321168])